before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 3.2.9
  - ruby-head
  - jruby-19mode
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
